/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: '#131313',
        mint: '#3cffd0',
        ultraviolet: '#5200ff',
        'ultraviolet-transparent': 'rgba(82, 0, 255, 0.9)',
        'mint-border': '#309875',
        'deep-link-blue': '#3860be',
        'purple-rule': '#3d00bf',
        slate: '#2d2d2d',
        'image-frame': '#313131',
        'dim-gray': '#8c8c8c',
        'focus-cyan': '#1eaedb',
        'text-primary': '#ffffff',
        'text-secondary': '#949494',
        'text-muted': '#e9e9e9',
        'text-inverted': '#131313',
        'accent-yellow': '#ffe600',
        'accent-pink': '#ff6eb4',
        'accent-orange': '#ff6b35',
      },
      borderRadius: {
        2: '2px',
        3: '3px',
        4: '4px',
        20: '20px',
        24: '24px',
        30: '30px',
        40: '40px',
        half: '50%',
      },
      spacing: {
        1: '1px',
        2: '2px',
        4: '4px',
        5: '5px',
        6: '6px',
        8: '8px',
        9: '9px',
        10: '10px',
        12: '12px',
        14: '14px',
        15: '15px',
        16: '16px',
        20: '20px',
        24: '24px',
        25: '25px',
        32: '32px',
        40: '40px',
        48: '48px',
        64: '64px',
      },
      fontFamily: {
        display: ["'Bebas Neue'", 'Impact', 'Helvetica', 'sans-serif'],
        sans: ["'Space Grotesk'", 'Helvetica', 'Arial', 'sans-serif'],
        mono: ["'Space Mono'", "'Courier New'", 'Courier', 'monospace'],
      },
    },
  },
  plugins: [],
};
