/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464554',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#767586',
        'outline-variant': '#c7c4d7',
        'surface-tint': '#494bd6',
        primary: '#4648d4',
        'on-primary': '#ffffff',
        'primary-container': '#6063ee',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#c0c1ff',
        secondary: '#5c5f61',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e3e5',
        'on-secondary-container': '#626567',
        tertiary: '#904900',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b55d00',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#e1e0ff',
        'primary-fixed-dim': '#c0c1ff',
        'on-primary-fixed': '#07006c',
        'on-primary-fixed-variant': '#2f2ebe',
        'secondary-fixed': '#e0e3e5',
        'secondary-fixed-dim': '#c4c7c9',
        'on-secondary-fixed': '#191c1e',
        'on-secondary-fixed-variant': '#444749',
        'tertiary-fixed': '#ffdcc5',
        'tertiary-fixed-dim': '#ffb783',
        'on-tertiary-fixed': '#301400',
        'on-tertiary-fixed-variant': '#703700',
        background: '#f8f9ff',
        'on-background': '#0b1c30',
        'surface-variant': '#d3e4fe',
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
      spacing: {
        lg: '40px',
        margin: '32px',
        md: '24px',
        base: '8px',
        gutter: '24px',
        xl: '64px',
        xs: '4px',
        sm: '12px',
      },
      fontFamily: {
        'label-sm': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-sm': [
          '11px',
          { lineHeight: '14px', letterSpacing: '0', fontWeight: '500' },
        ],
        'body-sm': [
          '14px',
          { lineHeight: '20px', letterSpacing: '0', fontWeight: '400' },
        ],
        'body-md': [
          '16px',
          { lineHeight: '24px', letterSpacing: '0', fontWeight: '400' },
        ],
        'headline-sm': [
          '20px',
          { lineHeight: '28px', letterSpacing: '0', fontWeight: '500' },
        ],
        'headline-lg': [
          '32px',
          { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' },
        ],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' },
        ],
        'body-lg': [
          '18px',
          { lineHeight: '28px', letterSpacing: '0', fontWeight: '400' },
        ],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
      },
      boxShadow: {
        card: '0 4px 12px rgba(70, 72, 212, 0.04)',
      },
    },
  },
  plugins: [],
};
